// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/sample.proto

public final class Sample {
  private Sample() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SampleMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .MetaData metadata = 25;
    /**
     * <code>optional .MetaData metadata = 25;</code>
     */
    boolean hasMetadata();
    /**
     * <code>optional .MetaData metadata = 25;</code>
     */
    Sample.MetaData getMetadata();
    /**
     * <code>optional .MetaData metadata = 25;</code>
     */
    Sample.MetaDataOrBuilder getMetadataOrBuilder();

    // optional string log_tag = 26;
    /**
     * <code>optional string log_tag = 26;</code>
     */
    boolean hasLogTag();
    /**
     * <code>optional string log_tag = 26;</code>
     */
    java.lang.String getLogTag();
    /**
     * <code>optional string log_tag = 26;</code>
     */
    com.google.protobuf.ByteString
        getLogTagBytes();

    // optional string local_ip = 129;
    /**
     * <code>optional string local_ip = 129;</code>
     *
     * <pre>
     *optional fixed32 local_ip = 129 [(autosetter) = "ip_to_decimal(odp::extract_param(#local_ip))"];
     * </pre>
     */
    boolean hasLocalIp();
    /**
     * <code>optional string local_ip = 129;</code>
     *
     * <pre>
     *optional fixed32 local_ip = 129 [(autosetter) = "ip_to_decimal(odp::extract_param(#local_ip))"];
     * </pre>
     */
    java.lang.String getLocalIp();
    /**
     * <code>optional string local_ip = 129;</code>
     *
     * <pre>
     *optional fixed32 local_ip = 129 [(autosetter) = "ip_to_decimal(odp::extract_param(#local_ip))"];
     * </pre>
     */
    com.google.protobuf.ByteString
        getLocalIpBytes();
  }
  /**
   * Protobuf type {@code SampleMessage}
   *
   * <pre>
   * 主message名称需要修改成同日志名称一致。
   * </pre>
   */
  public static final class SampleMessage extends
      com.google.protobuf.GeneratedMessage
      implements SampleMessageOrBuilder {
    // Use SampleMessage.newBuilder() to construct.
    private SampleMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SampleMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SampleMessage defaultInstance;
    public static SampleMessage getDefaultInstance() {
      return defaultInstance;
    }

    public SampleMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SampleMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 202: {
              Sample.MetaData.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = metadata_.toBuilder();
              }
              metadata_ = input.readMessage(Sample.MetaData.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(metadata_);
                metadata_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 210: {
              bitField0_ |= 0x00000002;
              logTag_ = input.readBytes();
              break;
            }
            case 1034: {
              bitField0_ |= 0x00000004;
              localIp_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Sample.internal_static_SampleMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Sample.internal_static_SampleMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Sample.SampleMessage.class, Sample.SampleMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<SampleMessage> PARSER =
        new com.google.protobuf.AbstractParser<SampleMessage>() {
      public SampleMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SampleMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SampleMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .MetaData metadata = 25;
    public static final int METADATA_FIELD_NUMBER = 25;
    private Sample.MetaData metadata_;
    /**
     * <code>optional .MetaData metadata = 25;</code>
     */
    public boolean hasMetadata() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .MetaData metadata = 25;</code>
     */
    public Sample.MetaData getMetadata() {
      return metadata_;
    }
    /**
     * <code>optional .MetaData metadata = 25;</code>
     */
    public Sample.MetaDataOrBuilder getMetadataOrBuilder() {
      return metadata_;
    }

    // optional string log_tag = 26;
    public static final int LOG_TAG_FIELD_NUMBER = 26;
    private java.lang.Object logTag_;
    /**
     * <code>optional string log_tag = 26;</code>
     */
    public boolean hasLogTag() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string log_tag = 26;</code>
     */
    public java.lang.String getLogTag() {
      java.lang.Object ref = logTag_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          logTag_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string log_tag = 26;</code>
     */
    public com.google.protobuf.ByteString
        getLogTagBytes() {
      java.lang.Object ref = logTag_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        logTag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string local_ip = 129;
    public static final int LOCAL_IP_FIELD_NUMBER = 129;
    private java.lang.Object localIp_;
    /**
     * <code>optional string local_ip = 129;</code>
     *
     * <pre>
     *optional fixed32 local_ip = 129 [(autosetter) = "ip_to_decimal(odp::extract_param(#local_ip))"];
     * </pre>
     */
    public boolean hasLocalIp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string local_ip = 129;</code>
     *
     * <pre>
     *optional fixed32 local_ip = 129 [(autosetter) = "ip_to_decimal(odp::extract_param(#local_ip))"];
     * </pre>
     */
    public java.lang.String getLocalIp() {
      java.lang.Object ref = localIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          localIp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string local_ip = 129;</code>
     *
     * <pre>
     *optional fixed32 local_ip = 129 [(autosetter) = "ip_to_decimal(odp::extract_param(#local_ip))"];
     * </pre>
     */
    public com.google.protobuf.ByteString
        getLocalIpBytes() {
      java.lang.Object ref = localIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        localIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      metadata_ = Sample.MetaData.getDefaultInstance();
      logTag_ = "";
      localIp_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(25, metadata_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(26, getLogTagBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(129, getLocalIpBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(25, metadata_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(26, getLogTagBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(129, getLocalIpBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Sample.SampleMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Sample.SampleMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Sample.SampleMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Sample.SampleMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Sample.SampleMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Sample.SampleMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Sample.SampleMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Sample.SampleMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Sample.SampleMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Sample.SampleMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Sample.SampleMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SampleMessage}
     *
     * <pre>
     * 主message名称需要修改成同日志名称一致。
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Sample.SampleMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Sample.internal_static_SampleMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Sample.internal_static_SampleMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Sample.SampleMessage.class, Sample.SampleMessage.Builder.class);
      }

      // Construct using Sample.SampleMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMetadataFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (metadataBuilder_ == null) {
          metadata_ = Sample.MetaData.getDefaultInstance();
        } else {
          metadataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        logTag_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        localIp_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Sample.internal_static_SampleMessage_descriptor;
      }

      public Sample.SampleMessage getDefaultInstanceForType() {
        return Sample.SampleMessage.getDefaultInstance();
      }

      public Sample.SampleMessage build() {
        Sample.SampleMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Sample.SampleMessage buildPartial() {
        Sample.SampleMessage result = new Sample.SampleMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (metadataBuilder_ == null) {
          result.metadata_ = metadata_;
        } else {
          result.metadata_ = metadataBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.logTag_ = logTag_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.localIp_ = localIp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Sample.SampleMessage) {
          return mergeFrom((Sample.SampleMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Sample.SampleMessage other) {
        if (other == Sample.SampleMessage.getDefaultInstance()) return this;
        if (other.hasMetadata()) {
          mergeMetadata(other.getMetadata());
        }
        if (other.hasLogTag()) {
          bitField0_ |= 0x00000002;
          logTag_ = other.logTag_;
          onChanged();
        }
        if (other.hasLocalIp()) {
          bitField0_ |= 0x00000004;
          localIp_ = other.localIp_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Sample.SampleMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Sample.SampleMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .MetaData metadata = 25;
      private Sample.MetaData metadata_ = Sample.MetaData.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          Sample.MetaData, Sample.MetaData.Builder, Sample.MetaDataOrBuilder> metadataBuilder_;
      /**
       * <code>optional .MetaData metadata = 25;</code>
       */
      public boolean hasMetadata() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .MetaData metadata = 25;</code>
       */
      public Sample.MetaData getMetadata() {
        if (metadataBuilder_ == null) {
          return metadata_;
        } else {
          return metadataBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .MetaData metadata = 25;</code>
       */
      public Builder setMetadata(Sample.MetaData value) {
        if (metadataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          metadata_ = value;
          onChanged();
        } else {
          metadataBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .MetaData metadata = 25;</code>
       */
      public Builder setMetadata(
          Sample.MetaData.Builder builderForValue) {
        if (metadataBuilder_ == null) {
          metadata_ = builderForValue.build();
          onChanged();
        } else {
          metadataBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .MetaData metadata = 25;</code>
       */
      public Builder mergeMetadata(Sample.MetaData value) {
        if (metadataBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              metadata_ != Sample.MetaData.getDefaultInstance()) {
            metadata_ =
              Sample.MetaData.newBuilder(metadata_).mergeFrom(value).buildPartial();
          } else {
            metadata_ = value;
          }
          onChanged();
        } else {
          metadataBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .MetaData metadata = 25;</code>
       */
      public Builder clearMetadata() {
        if (metadataBuilder_ == null) {
          metadata_ = Sample.MetaData.getDefaultInstance();
          onChanged();
        } else {
          metadataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .MetaData metadata = 25;</code>
       */
      public Sample.MetaData.Builder getMetadataBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getMetadataFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .MetaData metadata = 25;</code>
       */
      public Sample.MetaDataOrBuilder getMetadataOrBuilder() {
        if (metadataBuilder_ != null) {
          return metadataBuilder_.getMessageOrBuilder();
        } else {
          return metadata_;
        }
      }
      /**
       * <code>optional .MetaData metadata = 25;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          Sample.MetaData, Sample.MetaData.Builder, Sample.MetaDataOrBuilder> 
          getMetadataFieldBuilder() {
        if (metadataBuilder_ == null) {
          metadataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Sample.MetaData, Sample.MetaData.Builder, Sample.MetaDataOrBuilder>(
                  metadata_,
                  getParentForChildren(),
                  isClean());
          metadata_ = null;
        }
        return metadataBuilder_;
      }

      // optional string log_tag = 26;
      private java.lang.Object logTag_ = "";
      /**
       * <code>optional string log_tag = 26;</code>
       */
      public boolean hasLogTag() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string log_tag = 26;</code>
       */
      public java.lang.String getLogTag() {
        java.lang.Object ref = logTag_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          logTag_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string log_tag = 26;</code>
       */
      public com.google.protobuf.ByteString
          getLogTagBytes() {
        java.lang.Object ref = logTag_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          logTag_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string log_tag = 26;</code>
       */
      public Builder setLogTag(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        logTag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string log_tag = 26;</code>
       */
      public Builder clearLogTag() {
        bitField0_ = (bitField0_ & ~0x00000002);
        logTag_ = getDefaultInstance().getLogTag();
        onChanged();
        return this;
      }
      /**
       * <code>optional string log_tag = 26;</code>
       */
      public Builder setLogTagBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        logTag_ = value;
        onChanged();
        return this;
      }

      // optional string local_ip = 129;
      private java.lang.Object localIp_ = "";
      /**
       * <code>optional string local_ip = 129;</code>
       *
       * <pre>
       *optional fixed32 local_ip = 129 [(autosetter) = "ip_to_decimal(odp::extract_param(#local_ip))"];
       * </pre>
       */
      public boolean hasLocalIp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string local_ip = 129;</code>
       *
       * <pre>
       *optional fixed32 local_ip = 129 [(autosetter) = "ip_to_decimal(odp::extract_param(#local_ip))"];
       * </pre>
       */
      public java.lang.String getLocalIp() {
        java.lang.Object ref = localIp_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          localIp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string local_ip = 129;</code>
       *
       * <pre>
       *optional fixed32 local_ip = 129 [(autosetter) = "ip_to_decimal(odp::extract_param(#local_ip))"];
       * </pre>
       */
      public com.google.protobuf.ByteString
          getLocalIpBytes() {
        java.lang.Object ref = localIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          localIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string local_ip = 129;</code>
       *
       * <pre>
       *optional fixed32 local_ip = 129 [(autosetter) = "ip_to_decimal(odp::extract_param(#local_ip))"];
       * </pre>
       */
      public Builder setLocalIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        localIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string local_ip = 129;</code>
       *
       * <pre>
       *optional fixed32 local_ip = 129 [(autosetter) = "ip_to_decimal(odp::extract_param(#local_ip))"];
       * </pre>
       */
      public Builder clearLocalIp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        localIp_ = getDefaultInstance().getLocalIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string local_ip = 129;</code>
       *
       * <pre>
       *optional fixed32 local_ip = 129 [(autosetter) = "ip_to_decimal(odp::extract_param(#local_ip))"];
       * </pre>
       */
      public Builder setLocalIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        localIp_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SampleMessage)
    }

    static {
      defaultInstance = new SampleMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SampleMessage)
  }

  public interface MetaDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 log_module_id = 1 [default = 1175];
    /**
     * <code>optional int32 log_module_id = 1 [default = 1175];</code>
     */
    boolean hasLogModuleId();
    /**
     * <code>optional int32 log_module_id = 1 [default = 1175];</code>
     */
    int getLogModuleId();

    // optional string log_name = 2 [default = "image_wantu_odp_app"];
    /**
     * <code>optional string log_name = 2 [default = "image_wantu_odp_app"];</code>
     */
    boolean hasLogName();
    /**
     * <code>optional string log_name = 2 [default = "image_wantu_odp_app"];</code>
     */
    java.lang.String getLogName();
    /**
     * <code>optional string log_name = 2 [default = "image_wantu_odp_app"];</code>
     */
    com.google.protobuf.ByteString
        getLogNameBytes();

    // optional string product_name = 3 [default = "image"];
    /**
     * <code>optional string product_name = 3 [default = "image"];</code>
     */
    boolean hasProductName();
    /**
     * <code>optional string product_name = 3 [default = "image"];</code>
     */
    java.lang.String getProductName();
    /**
     * <code>optional string product_name = 3 [default = "image"];</code>
     */
    com.google.protobuf.ByteString
        getProductNameBytes();
  }
  /**
   * Protobuf type {@code MetaData}
   */
  public static final class MetaData extends
      com.google.protobuf.GeneratedMessage
      implements MetaDataOrBuilder {
    // Use MetaData.newBuilder() to construct.
    private MetaData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MetaData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MetaData defaultInstance;
    public static MetaData getDefaultInstance() {
      return defaultInstance;
    }

    public MetaData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MetaData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              logModuleId_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              logName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              productName_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Sample.internal_static_MetaData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Sample.internal_static_MetaData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Sample.MetaData.class, Sample.MetaData.Builder.class);
    }

    public static com.google.protobuf.Parser<MetaData> PARSER =
        new com.google.protobuf.AbstractParser<MetaData>() {
      public MetaData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MetaData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MetaData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 log_module_id = 1 [default = 1175];
    public static final int LOG_MODULE_ID_FIELD_NUMBER = 1;
    private int logModuleId_;
    /**
     * <code>optional int32 log_module_id = 1 [default = 1175];</code>
     */
    public boolean hasLogModuleId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 log_module_id = 1 [default = 1175];</code>
     */
    public int getLogModuleId() {
      return logModuleId_;
    }

    // optional string log_name = 2 [default = "image_wantu_odp_app"];
    public static final int LOG_NAME_FIELD_NUMBER = 2;
    private java.lang.Object logName_;
    /**
     * <code>optional string log_name = 2 [default = "image_wantu_odp_app"];</code>
     */
    public boolean hasLogName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string log_name = 2 [default = "image_wantu_odp_app"];</code>
     */
    public java.lang.String getLogName() {
      java.lang.Object ref = logName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          logName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string log_name = 2 [default = "image_wantu_odp_app"];</code>
     */
    public com.google.protobuf.ByteString
        getLogNameBytes() {
      java.lang.Object ref = logName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        logName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string product_name = 3 [default = "image"];
    public static final int PRODUCT_NAME_FIELD_NUMBER = 3;
    private java.lang.Object productName_;
    /**
     * <code>optional string product_name = 3 [default = "image"];</code>
     */
    public boolean hasProductName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string product_name = 3 [default = "image"];</code>
     */
    public java.lang.String getProductName() {
      java.lang.Object ref = productName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          productName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string product_name = 3 [default = "image"];</code>
     */
    public com.google.protobuf.ByteString
        getProductNameBytes() {
      java.lang.Object ref = productName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      logModuleId_ = 1175;
      logName_ = "image_wantu_odp_app";
      productName_ = "image";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, logModuleId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getLogNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getProductNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, logModuleId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getLogNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getProductNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Sample.MetaData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Sample.MetaData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Sample.MetaData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Sample.MetaData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Sample.MetaData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Sample.MetaData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Sample.MetaData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Sample.MetaData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Sample.MetaData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Sample.MetaData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Sample.MetaData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MetaData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Sample.MetaDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Sample.internal_static_MetaData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Sample.internal_static_MetaData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Sample.MetaData.class, Sample.MetaData.Builder.class);
      }

      // Construct using Sample.MetaData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        logModuleId_ = 1175;
        bitField0_ = (bitField0_ & ~0x00000001);
        logName_ = "image_wantu_odp_app";
        bitField0_ = (bitField0_ & ~0x00000002);
        productName_ = "image";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Sample.internal_static_MetaData_descriptor;
      }

      public Sample.MetaData getDefaultInstanceForType() {
        return Sample.MetaData.getDefaultInstance();
      }

      public Sample.MetaData build() {
        Sample.MetaData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Sample.MetaData buildPartial() {
        Sample.MetaData result = new Sample.MetaData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.logModuleId_ = logModuleId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.logName_ = logName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.productName_ = productName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Sample.MetaData) {
          return mergeFrom((Sample.MetaData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Sample.MetaData other) {
        if (other == Sample.MetaData.getDefaultInstance()) return this;
        if (other.hasLogModuleId()) {
          setLogModuleId(other.getLogModuleId());
        }
        if (other.hasLogName()) {
          bitField0_ |= 0x00000002;
          logName_ = other.logName_;
          onChanged();
        }
        if (other.hasProductName()) {
          bitField0_ |= 0x00000004;
          productName_ = other.productName_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Sample.MetaData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Sample.MetaData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 log_module_id = 1 [default = 1175];
      private int logModuleId_ = 1175;
      /**
       * <code>optional int32 log_module_id = 1 [default = 1175];</code>
       */
      public boolean hasLogModuleId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 log_module_id = 1 [default = 1175];</code>
       */
      public int getLogModuleId() {
        return logModuleId_;
      }
      /**
       * <code>optional int32 log_module_id = 1 [default = 1175];</code>
       */
      public Builder setLogModuleId(int value) {
        bitField0_ |= 0x00000001;
        logModuleId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 log_module_id = 1 [default = 1175];</code>
       */
      public Builder clearLogModuleId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        logModuleId_ = 1175;
        onChanged();
        return this;
      }

      // optional string log_name = 2 [default = "image_wantu_odp_app"];
      private java.lang.Object logName_ = "image_wantu_odp_app";
      /**
       * <code>optional string log_name = 2 [default = "image_wantu_odp_app"];</code>
       */
      public boolean hasLogName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string log_name = 2 [default = "image_wantu_odp_app"];</code>
       */
      public java.lang.String getLogName() {
        java.lang.Object ref = logName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          logName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string log_name = 2 [default = "image_wantu_odp_app"];</code>
       */
      public com.google.protobuf.ByteString
          getLogNameBytes() {
        java.lang.Object ref = logName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          logName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string log_name = 2 [default = "image_wantu_odp_app"];</code>
       */
      public Builder setLogName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        logName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string log_name = 2 [default = "image_wantu_odp_app"];</code>
       */
      public Builder clearLogName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        logName_ = getDefaultInstance().getLogName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string log_name = 2 [default = "image_wantu_odp_app"];</code>
       */
      public Builder setLogNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        logName_ = value;
        onChanged();
        return this;
      }

      // optional string product_name = 3 [default = "image"];
      private java.lang.Object productName_ = "image";
      /**
       * <code>optional string product_name = 3 [default = "image"];</code>
       */
      public boolean hasProductName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string product_name = 3 [default = "image"];</code>
       */
      public java.lang.String getProductName() {
        java.lang.Object ref = productName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          productName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string product_name = 3 [default = "image"];</code>
       */
      public com.google.protobuf.ByteString
          getProductNameBytes() {
        java.lang.Object ref = productName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          productName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string product_name = 3 [default = "image"];</code>
       */
      public Builder setProductName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        productName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string product_name = 3 [default = "image"];</code>
       */
      public Builder clearProductName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        productName_ = getDefaultInstance().getProductName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string product_name = 3 [default = "image"];</code>
       */
      public Builder setProductNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        productName_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MetaData)
    }

    static {
      defaultInstance = new MetaData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MetaData)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SampleMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SampleMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MetaData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MetaData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037src/main/resources/sample.proto\"P\n\rSam" +
      "pleMessage\022\033\n\010metadata\030\031 \001(\0132\t.MetaData\022" +
      "\017\n\007log_tag\030\032 \001(\t\022\021\n\010local_ip\030\201\001 \001(\t\"k\n\010M" +
      "etaData\022\033\n\rlog_module_id\030\001 \001(\005:\0041175\022%\n\010" +
      "log_name\030\002 \001(\t:\023image_wantu_odp_app\022\033\n\014p" +
      "roduct_name\030\003 \001(\t:\005image"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_SampleMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_SampleMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SampleMessage_descriptor,
              new java.lang.String[] { "Metadata", "LogTag", "LocalIp", });
          internal_static_MetaData_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_MetaData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MetaData_descriptor,
              new java.lang.String[] { "LogModuleId", "LogName", "ProductName", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
