mode:
  production


application:
    controllerNames: org.apache.spark.iwaimai.spark.yarn.controller.DriverController
    static:
        enable: false
    template:
        engine:
           enable: false


http:
    disable: false
    class:
        port: org.apache.spark.iwaimai.spark.yarn.config.RandomPortGenerator
thrift:
    disable: true
dubbo:
    disable: true

production:
  datasources:
    mysql:
      disable: true
    mongodb:
      disable: true
    redis:
      disable: true

